name: CI Checks
on:
  push:
    branches: [ main, test, modify-workflow ]
  pull_request:
  workflow_dispatch:


jobs:
  check-inputs-outputs:
    name: Check Input and Output enums
    runs-on: ubuntu-20.04
    env:
      COMMITTED_FILENAME: src/generated/inputs-outputs.ts
      GENERATED_FILENAME: action-generated-ins-outs.ts

    steps:
      - uses: actions/checkout@v2

      - name: Run input output checker
        uses: divyansh42/common/action-io-generator@add-io-checker
        with:
          io_file: src/generated/inputs-outputs.ts

  check-dist:
    name: Check Distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Check Distribution
        uses: tetchel/bundle-verifier-action@v0.0.2
        with:
          bundle_file: dist/index.js
          bundle_command: "npm run bundle"

  lint:
    name: Run ESLint
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: npm ci

        - name: Run ESLint
          run: npm run lint
